### ISSUE TITLE
عدم تغیر 

### ISSUE THREAD

**Issue by soroushsafaar** [oXIIIo/marzban-template#1]
من تمامی مراحل رو رفتم ولی هیچ تغیری ایجاد نشد محتوای فایل .env دو خط آخر هم چک کردم 
'CUSTOM_TEMPLATES_DIRECTORY="/var/lib/marzban/templates/"'
'CLASH_SUBSCRIPTION_TEMPLATE="clash/template.yml"'
اومده بود.

**Comment by oXIIIo** [comment]
سلام مرزبان رو ری استارت کردین؟
بعد از restart مزبان اروری میگیرین؟
از چه نسخه ای از کلش متا استفاده میکنید؟

**Comment by soroushsafaar** [comment]
مرزبان رو ری استارت میکنم اروری هم نمیگیرم .
کانفیگ خاصی باید بعدش اضافه بشه ؟
