### ISSUE TITLE
آیا برای منی ک از ساب هاست استفاده کردم هم اعمال میشه؟

### ISSUE THREAD

**Issue by abedin70** [oXIIIo/marzban-template#2]
من از هاست برای ساب استفاده میکنم.
همون کد پیشفرض مرزبان هست و اصلا تمپلت تغییر ندادم!
اگه اینو بزنم تو هاست هم اعمال میشه؟
یا باید کار خاصی انجام بدم؟
یا اصلا مشکلی پیش نمیاره!!؟

**Comment by oXIIIo** [comment]
> اگه اینو بزنم تو هاست هم اعمال میشه؟ یا باید کار خاصی انجام بدم؟

از هاست استفاده نکردم اگر user-agent رو میفرسته و نتیجه رو به همون صورت نشون میده میتونی استفاده کنی.
> یا اصلا مشکلی پیش نمیاره!!؟

اگر user-agent نفرسته فایل کانفیگ مربوط به کلاینت نشون داده نمیشه ولی مشکلی خاصی ایجاد نمیشه فقط اون کلاینت ارور میده.
مثلا لینک سابسکریپشن روی کلش کار نمیکنه ولی روی v2rayng مشکلی نداره.

**Comment by abedin70** [comment]
> > اگه اینو بزنم تو هاست هم اعمال میشه؟ یا باید کار خاصی انجام بدم؟
> 
> از هاست استفاده نکردم اگر user-agent رو میفرسته و نتیجه رو به همون صورت نشون میده میتونی استفاده کنی.
> 
> > یا اصلا مشکلی پیش نمیاره!!؟
> 
> اگر user-agent نفرسته فایل کانفیگ مربوط به کلاینت نشون داده نمیشه ولی مشکلی خاصی ایجاد نمیشه فقط اون کلاینت ارور میده. مثلا لینک سابسکریپشن روی کلش کار نمیکنه ولی روی v2rayng مشکلی نداره.

اینو استفاده کردم
https://github.com/Gozargah/Marzban/discussions/26#discussion-4831958
منظورتونو متوجه نشدم

**Comment by oXIIIo** [comment]
تا جاییکه من کدشونو دیدم فک نکنم مشکلی داشته باشه
