### ISSUE TITLE
اصلاح مدت زمان باقیمانده

### ISSUE THREAD

**Issue by RezaKardoost** [oXIIIo/marzban-template#3]
زمانی که انقضای اکانت به کمتر از ۱ روز میرسد، زمان باقیمانده را 0 روز نمایش میدهد که برای کاربر کمی مبهم است. بهتره در کنار نمایش روز، نمایش ساعت رو هم قرار بدهید. مثلا ۵ روز و ۲۳ ساعت.

![image](https://github.com/oXIIIo/marzban-template/assets/15872932/aa235dde-e9f7-4edc-9a13-4694eadaafed)

![image](https://github.com/oXIIIo/marzban-template/assets/15872932/37eac2bd-35ed-44d2-a94d-3f65a014983a)

**Comment by oXIIIo** [comment]
سلام
تغییراتی ک خواستین اعمال شد میتونید اپدیت کنید.
فقط کافیه دستور زیر رو توی ترمینال سرورتون بزنید:
```sh
sudo wget -N -P /var/lib/marzban/templates/subscription/ https://raw.githubusercontent.com/oXIIIo/marzban-template/master/subscription/index.html
```

**Comment by RezaKardoost** [comment]
ممنون بابت اعمال تغییرات و بروزرسانی🙏🙏🙏
فقط زمانی که اکانت  منقضی شده باشد، مدت زمان باقیمانده اشتباه نمایش داده می‌شود:

![image](https://github.com/oXIIIo/marzban-template/assets/15872932/c74187b0-d5b2-4b2e-bf1b-466a94057c49)

من وب دولوپر نیستم اما تونستم با اضافه کردن یک شرط (if current_timestamp >= user.expire) مشکل را رفع کنم. زمانی که اکانت منقضی میشه، عدد ۰ را نمایش میدهد. باز شما خودتون هر طور که مناسب تر است اصلاحش کنید.

```
{% if not user.expire %}
∞
{% else %}
    {% set current_timestamp = now().timestamp() %}
    {% set remaining_seconds = user.expire - current_timestamp %}
    {% set remaining_days = remaining_seconds // (24 * 3600) %}
    {% set remaining_hours = (remaining_seconds % (24 * 3600)) // 3600 %}
    {% set remaining_minutes = (remaining_seconds % 3600) // 60 %}

    {% if current_timestamp >= user.expire %} 

        0
    {% else %}
        {% if remaining_days >= 1 %}
            {{ remaining_days | int }} روز {{ remaining_hours | int }} ساعت
        {% else %}
            {{ remaining_hours | int }} ساعت {{ remaining_minutes | int }} دقیقه
        {% endif %}
    {% endif %}
{% endif %}</div>
```
