### ISSUE TITLE
progress bar for data usage

### ISSUE THREAD

**Issue by RezaKardoost** [oXIIIo/marzban-template#4]
خیلی خوب میشه اگر برای حجم باقیمانده،  یک progress bar نمایش داده شود. اینطور با یک  نگاه راحت مشخض میشه که چقدر از حجم اکانت مصرف و چقدر باقیمانده است.

**Comment by oXIIIo** [comment]
سلام ممنون از پیشنهادتون، progress bar اضافه شد، میتونید اپدیت کنید.
