### ISSUE TITLE
مشکل در نمایش نام کاربری طولانی

### ISSUE THREAD

**Issue by RezaKardoost** [oXIIIo/marzban-template#5]
هنگامی که نام کاربری طولانی باشد، نام کاربری در خط دوم نوشته می‌شوند اما فاصله آن با خط اول کم است و متن تو در تو میشه. از لحاظ ظاهری بهتره کمی فاصله در نظر گرفت تا خوانا تر شه.

عکس نمونه:
![image](https://github.com/oXIIIo/marzban-template/assets/15872932/4f819eb1-712a-4373-9e60-dd026b3748fb)

**Comment by oXIIIo** [comment]
این مشکل حل شد، اپدیت کنید.
مرسی ک اطلاع دادین.
