### ISSUE TITLE
باگ در نمایش مدت زمان باقیمانده برای اکانت های منقضی شده

### ISSUE THREAD

**Issue by RezaKardoost** [oXIIIo/marzban-template#6]
ممنون بابت اعمال تغییرات و بروزرسانی🙏🙏🙏
فقط زمانی که اکانت  منقضی شده باشد، مدت زمان باقیمانده اشتباه نمایش داده می‌شود:

![image](https://github.com/oXIIIo/marzban-template/assets/15872932/c74187b0-d5b2-4b2e-bf1b-466a94057c49)

من وب دولوپر نیستم اما تونستم با اضافه کردن یک شرط (if current_timestamp >= user.expire) مشکل را رفع کنم. زمانی که اکانت منقضی میشه، عدد ۰ را نمایش میدهد. باز شما خودتون هر طور که مناسب تر است اصلاحش کنید.

```
{% if not user.expire %}
∞
{% else %}
    {% set current_timestamp = now().timestamp() %}
    {% set remaining_seconds = user.expire - current_timestamp %}
    {% set remaining_days = remaining_seconds // (24 * 3600) %}
    {% set remaining_hours = (remaining_seconds % (24 * 3600)) // 3600 %}
    {% set remaining_minutes = (remaining_seconds % 3600) // 60 %}

    {% if current_timestamp >= user.expire %} 

        0
    {% else %}
        {% if remaining_days >= 1 %}
            {{ remaining_days | int }} روز {{ remaining_hours | int }} ساعت
        {% else %}
            {{ remaining_hours | int }} ساعت {{ remaining_minutes | int }} دقیقه
        {% endif %}
    {% endif %}
{% endif %}</div>
```

**Comment by oXIIIo** [comment]
ممنون که اطلاع دادین، این مشکل رو حل کردم میتونید تست کنید.
