### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by abedin70** [oXIIIo/marzban-template#8]
یکم جمعش کن ک همه تو نگاه اول مشخص باشه و نیازی ب بالا پایین کردن صفحه نباشه!
ممنون از زحماتت

**Comment by oXIIIo** [comment]
سلام
لیست برنامه ها بصورت کشویی شده.
میتونید اپدیت کنید و تستش کنید

**Comment by abedin70** [comment]
عالیه دمت شما گرم

**Comment by abedin70** [comment]
> سلام لیست برنامه ها بصورت کشویی شده. میتونید اپدیت کنید و تستش کنید

دم شما گرم
